//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemeLord.Configuration.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class GoogleApiSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GoogleApiSettings defaultInstance = ((GoogleApiSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GoogleApiSettings())));
        
        public static GoogleApiSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("462863838838-5q24j1bjcml1k7sfhvetsbsh57jvvada.apps.googleusercontent.com")]
        public string client_id {
            get {
                return ((string)(this["client_id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("memelord-auth")]
        public string project_id {
            get {
                return ((string)(this["project_id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://accounts.google.com/o/oauth2/auth")]
        public string auth_uri {
            get {
                return ((string)(this["auth_uri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://accounts.google.com/o/oauth2/token")]
        public string token_uri {
            get {
                return ((string)(this["token_uri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.googleapis.com/oauth2/v1/certs")]
        public string auth_provider_x509_cert_url {
            get {
                return ((string)(this["auth_provider_x509_cert_url"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X5dXhcEcZ4zTuPUwu24DglTq")]
        public string client_secret {
            get {
                return ((string)(this["client_secret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44372/signin-google")]
        public string redirect_uris {
            get {
                return ((string)(this["redirect_uris"]));
            }
        }
    }
}
